### ISSUE TITLE
Repository cloned size is very large because of results zip files

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/BESTEST-GSR-ARCHIVE#12]
When switching to a different computer I realized that the results zip test case zip files make an otherwise light weight repository excessively large (10 GB). @Myoldmopar what do you think about storing the results in a separate repo named something like "BESTEST-GSR-bestest_zips". Then I can add it to the gitignore on this repo.

**Comment by Myoldmopar** [comment]
The zips should probably just be added as assets when you create a new release.  That way they are tied with the release itself, but not a part of the repo.  This alone won't fix the whole problem though, as those zip files are still in the history, so any clone will continue to have them.  The only way to address that would be to "recreate" the git history, eliminating those files and making commits along the way for each version.  Could be a dramatic step, but it would fix the size for the repo as a whole.

**Comment by DavidGoldwasser** [comment]
@Myoldmopar Thanks, I'll definitely implement what you suggest for future releases and will remove those files from the repo, and will give some thought to re-creating the history. I'm no too concerned too much about repo history even though 200 comments, they are mostly NREL. Maybe I could archive history on fork and then clean up this?

**Comment by DavidGoldwasser** [comment]
I may want to clean up PAT at some point as well in particular if I have an archive somewhere else.

**Comment by DavidGoldwasser** [comment]
@tijcolem helped me manage this. We made new repo without zips, moved zips to S3, renamed original repo to archive, and made new repo using the non-archive name. Now 150MB instead of 10GB checkout size. I added a note to this readme.md to point to other repo
